--this means get me the null values of the first table.
--LEFT OUTER JOIN => sadece soldaki fark kümesi.
SELECT FIRST_NAME,LAST_NAME,E.DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID
FROM EMPLOYEES E LEFT outer join DEPARTMENTS D
on E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID is null;


-- A FARK KÜMESİ &  B FARK KUMESİNİ VERİR.
--SADECE A DA OLANLARI VE SADECE B DE OLANLARI GETİRİYOR.KESİŞİM KÜMESI DAHİL DEĞİL.
SELECT * FROM CUSTOMER_MN FULL OUTER JOIN ADDRESS_MN
on CUSTOMER_MN.ADDRESS_ID = ADDRESS_MN.ADDRESS_ID
WHERE CUSTOMER_ID is null OR ADDRESS_MN.ADDRESS_ID IS NULL;

--get me firstname,lastname,departmentname, city
SELECT FIRST_NAME, LAST_NAME,DEPARTMENT_NAME,CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
on E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID;

--get me firstname,lastname,departmentname, city,countryname
SELECT FIRST_NAME, LAST_NAME,DEPARTMENT_NAME,CITY,COUNTRY_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
on E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID
join COUNTRIES C
on L.COUNTRY_ID = C.COUNTRY_ID



