SELECT FIRST_NAME,LAST_NAME,EMPLOYEE_ID,MANAGER_ID FROM EMPLOYEES;


                        --SELF JOIN  -- GETTING FROM THE SAME TABLE
--GET ME ALL EMPLOYEES FIRSTNAME, LASTNAME, AND MANAGERS FIRSTNAME AND LASTNAME
-- TABLOYU IKIYE BOLUP YAPIYORUZ E TABLOSUNU E1 E2 OLARAK 2 YE BOLUYORUZ/;
SELECT E1.FIRST_NAME,E1.LAST_NAME,E1.EMPLOYEE_ID,E2.MANAGER_ID,E2.FIRST_NAME,E2.LAST_NAME
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.MANAGER_ID=E2.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID;
