SELECT * FROM COUNTRIES;
SELECT MAX(SALARY) FROM EMPLOYEES;
CREATE TABLE SCRUMTEAM_MEHMETNOBEL(
    EMP_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR(30) NOT NULL ,
    LASTNAME VARCHAR(30),
    JOBTITLE VARCHAR(20)

);

SELECT * FROM SCRUMTEAM_MEHMETNOBEL;
INSERT INTO SCRUMTEAM_MEHMETNOBEL(EMP_ID, FIRSTNAME, LASTNAME, JOBTITLE)
VALUES (1,'MEHMET','NOBEL','SDET');

INSERT INTO SCRUMTEAM_MEHMETNOBEL(EMP_ID, FIRSTNAME, LASTNAME, JOBTITLE)
VALUES (2,'ESAD','TUNA','PO');
INSERT INTO SCRUMTEAM_MEHMETNOBEL VALUES (3, 'SEMIH','TUFAN','DEV');
INSERT INTO SCRUMTEAM_MEHMETNOBEL VALUES (4, 'SEMIH','TUFAN','SCRUM MASTER');
UPDATE SCRUMTEAM_MEHMETNOBEL
SET JOBTITLE='PO'
WHERE EMP_ID=2;

DELETE FROM SCRUMTEAM_MEHMETNOBEL
WHERE EMP_ID=1;

SELECT * FROM SCRUMTEAM_MEHMETNOBEL;
COMMIT;  -- TO SAVE THE FILES.

INSERT INTO SCRUMTEAM_MEHMETNOBEL VALUES (5,'ZEYNEP','SAFİYE','STUDENT');
SELECT * FROM SCRUMTEAM_MEHMETNOBEL;

INSERT INTO SCRUMTEAM_MEHMETNOBEL VALUES (1,'BURAK','ASLAN','STUDENT');

--adding new column
ALTER TABLE SCRUMTEAM_MEHMETNOBEL ADD SALARY INTEGER;

SELECT * FROM SCRUMTEAM_MEHMETNOBEL;

--updating the table VALUES
UPDATE SCRUMTEAM_MEHMETNOBEL
SET SALARY=18000
WHERE FIRSTNAME='BURAK';

SELECT * FROM SCRUMTEAM_MEHMETNOBEL;

UPDATE SCRUMTEAM_MEHMETNOBEL
SET SALARY=20000
WHERE EMP_ID=2;

UPDATE SCRUMTEAM_MEHMETNOBEL
SET SALARY=30000
WHERE EMP_ID=3;

UPDATE SCRUMTEAM_MEHMETNOBEL
SET SALARY=35000
WHERE EMP_ID=4;

UPDATE SCRUMTEAM_MEHMETNOBEL
SET SALARY=45000
WHERE EMP_ID=5;

SELECT * FROM SCRUMTEAM_MEHMETNOBEL;

--if we wanna update all the salary inf then it will be enogh to say like that:
-- UPDATE SCRUMTEAM_MEHMETNOBEL SET SALARY =22000;

--changing the Column name
ALTER TABLE SCRUMTEAM_MEHMETNOBEL RENAME COLUMN salary TO annual_Salary;

SELECT * FROM SCRUMTEAM_MEHMETNOBEL;

--DELETE/ DROP COLUMN
ALTER TABLE SCRUMTEAM_MEHMETNOBEL DROP COLUMN ANNUAL_SALARY;

--how to change table name
ALTER TABLE SCRUMTEAM_MEHMETNOBEL RENAME TO AGILE_TEAM;

SELECT * FROM AGILE_TEAM;

COMMIT ;

--TRUNCATE IF WE WANNA DELETE ALL THE DATA FROM THE TABLE BUT STILL KEEP THE TABLE STRUCTURE WE USE TRUNCATE
TRUNCATE TABLE AGILE_TEAM;

--TOTALLY DELETE THE TABLE
DROP TABLE AGILE_TEAM;

--AFTER THIS COMMAND SINCE WE DO NOT HAVE A TABLE IT WILL GIVE ERROR.

--DIFFERENCE BETW TRUNCATE AND DROP
--TRUNCATE KEEPS THE STRUCTURE
--BUT DROP DELETES EVERYTHING